workflows:
  ios-build:
    name: Skinnyman Softwares - Vistoria App (iOS)
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: 🔧 Preparar dependências Flutter
        script: flutter pub get

      - name: 📦 Compilar build iOS (.ipa)
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - hakaishin.cpv@gmail.com

